---

- name: execute headless script
  script: commen/roles/Execute/templates/headlessprocess.py
  when: process == "headless"


- name: execute full script
  script: commen/roles/Execute/templates/fullprocess.py
  when: process == "full"

...