---

# - name: execute full script
#   script: 
#     cmd: python3 ExecutePyimager/roles/Execute/templates/imager.py {{ optie1|lower }} {{ optie2|lower }}
#   when: 
#     - optie1 == "h" or optie1 == "f" or optie1 == "s" or optie1 == "H" or optie1 == "F" or optie1 == "S"
#     - optie2 == "r" or optie2 == "i" or optie2 == "R" or optie2 == "I"

- name: execute full script
  script: /home/brent/TestForAnsibleImager/testforpy/ExecutePyimager/roles/Execute/templates/imager.py h i
  args:
    executable: python3
  chdir: /home/brent/TestForAnsibleImager/testforpy/ExecutePyimager/roles/Execute/templates
...