---

- name: execute test script
  script: ../templates/testscript.py
  args:
    executable: python3
  when: process == "headless"

- name: execute headless script
  script: ../templates/headlessprocess.py
  args:
    executable: python3
  when: process == "headless"

- name: execute full script
  script: ../templates/fullprocess.py
  args:
    executable: python3
  when: process == "full"

...