---
- name: execute headless script
  script: ../templates/headlessprocess.py
  when: process == "headless"


- name: execute full script
  script: ../templates/fullprocess.py
  when: process == "full"

...