---

- name: "Check if package is installed"
  package_facts:
    manager: "auto"

- name: install using loop
  apt:
    name: "{{item}}"
    state: latest
  when: "'{{ item }}' not in ansible_facts.packages"
  loop: "{{installsapt}}"

- name: install using loop pip
  pip:
    name: "{{item}}"
    state: latest
  loop: "{{installspip}}"
  

...